title: Nataliia Dziubenko
description: Blog
blog_description:
  Every problem a developer faces in their daily routine might end up being an interesting journey.
  Sharing this journey with others makes it an awesome adventure.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 3

# Build settings
theme: minima
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme