title: Nataliia Dziubenko
description: Blog
blog_description:
  Curiosity brings us to a beautiful journey. Let's share this journey together.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://nataliiadziubenko.com # the base hostname & protocol for your site, e.g. http://example.com
paginate: 10
include:
  - .well-known
# Build settings
theme: minima
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme